### ISSUE TITLE
Speed comparison

### ISSUE THREAD

**Issue by Siilwyn** [shenanigans/node-surveil#1]
This package sounds really promising but what I really miss are some hard numbers in terms of speed/performance. Would be nice to see how much faster node-surveil is compared to other watchers such as [chokidar](https://github.com/paulmillr/chokidar) and [watch](https://github.com/mikeal/watch). Tested against a different amount of files. (e.g. 100, 500 and 1000 files)

[uBlock](https://github.com/chrisaljoudi/uBlock) does this really well with some bar charts.

**Comment by shenanigans** [comment]
I could spend hours making charts but it won't be as relevant as just trying the libs you're interested in using the node live shell. Admittedly it would be impressive to look at - in my use cases `surveil` established a new watch in ~300ms asynchronous where chokidar would take >10s and block the whole time. That could change, making my fancy graphs a lie, and frankly I don't care to watch other people's file watcher libs for changes. File watching is boring.
